// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using reactiveForm.web.Models;

namespace reactiveForm.web.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20200916182026_AddComentariosEvento")]
    partial class AddComentariosEvento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("reactiveForm.web.Models.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentarios");

                    b.Property<TimeSpan>("Duracion");

                    b.Property<DateTime>("FechaInicio");

                    b.Property<DateTime>("Fechafin");

                    b.Property<string>("IdsMedicos");

                    b.Property<string>("LugarEvento");

                    b.Property<int>("NoAsistentes");

                    b.Property<string>("Nombre");

                    b.Property<float>("PresupuestoAutorizado");

                    b.Property<string>("ProductosPromocionar");

                    b.Property<string>("Responsable");

                    b.HasKey("IdEvento");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("reactiveForm.web.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FechaNacimiento");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("reactiveForm.web.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<DateTime>("Vigencia");

                    b.Property<float>("costo");

                    b.HasKey("Id");

                    b.ToTable("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
